### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by mortendahl** [tf-encrypted/moose#1081]
`cargo outdated` shows that we currently have several dependencies that could be updated. This issue is about doing just that.

**Comment by jvmncs** [comment]
will be closed in #1152, the only dependency i didn't update is [notify](https://github.com/notify-rs/notify) bc they removed an API we were relying on for rudolph, see note here https://github.com/tf-encrypted/moose/pull/1152#issue-1435039530
